### ISSUE TITLE
Investigate Shipment Tracking entries/emails on wholesale orders.

### ISSUE THREAD

**Issue by JustinSainton** [zao-web/zao-woocommerce-wholesale#1]
Per  BT, 

ones where tracking came through only once: 235882, 235910, 235987

[3:53] 
(oo, on 236044 it came through 62 times!)

need to check into where WC Shipment Tracking emails/adds tracking.

**Comment by jtsternberg** [comment]
I don't believe this issue is _directly_ related to the wholesale plugin. But the issue has been mitigated with the client's project.
